version: '3.7'
services:
  app:
    image: 'node'
    working_dir: '/hostdir'
    volumes:
      - './:/hostdir'
    ports:
      - '3000:3000'
    command: bash -c 'npm install && npm run build && npm start'
