version: '3.8'
services:
  app:
    image: 'node:16'
    command: bash -c 'npm run test'
    working_dir: '/hostdir'
    volumes:
      - './:/hostdir'
    networks:
      - myproject_test
networks:
  myproject_test:
    external: true